### ISSUE TITLE
Build fails because of new compiletime constant

### ISSUE THREAD

**Issue by peq** [Crigges/HotN#5]
http://peeeq.de/hudson/job/Hotn/

**Comment by Crigges** [comment]
Yes i know iam just to lazy to push, thanks anyway!

**Comment by peq** [comment]
So you need some motivation?

As long as it is not compiling, I am free to introduce any backwards
incompatible change I want. :P

If it compiles I will only do minor incompatible changes like adding some
function or constant to the standard library.

**Comment by Crigges** [comment]
I fixed the bug a while ago just didn't pushed it yet. Now i did and the next build shoud succeed now :)
